### ISSUE TITLE
minsdkversion 28?

### ISSUE THREAD

**Issue by EchedelleLR** [ATryder/TEdit#14]
I came here after a failed upgrade in TEdit build of F-Droid.

The minimum needed version was 9.0 after a time I was using in Android 7.1.2.

Is there any intention to support these older versions again? They are still supported by Google updates perfectly.

**Comment by ATryder** [comment]
The purpose of updating TEdit to version 2.4.0 was to add support for Android 11 storage access restrictions. No new features or functionality have been added over TEdit 2.3.0 so you're not missing out on anything.

As I understand it, with Android 11, TEdit needs to ask the user to explicitly grant TEdit permission to access any directories on their device that they want to be able to browse and save files to. Additionally, TEdit must now use Android's DocumentFile class to list directory contents and open/save files. This can only be done after the user finds a folder to grant TEdit access to through Android's built in Files application.

It's works the same way TEdit 2.3.0 asked the user to grant permission to the SDcard, but now it does this for internal storage as well. Apparently applications can still use the old method of storage access if they target Android 10, but must use the new way if they target Android 11 or higher and, from what I hear, Google will be making it a requirement to target at least Android 11 next year so I figured I'd go ahead and implement the new storage access requirements.

With the new storage access requirements implented it became unnecessary to keep the old methods that were used to grant TEdit access to SDcards as that could now be done from the main browser view in TEdit just like any other folder. After I ripped all of that code out I realised that the means to grant an application permission to access a particular directory is not supported on all older devices.

Specifically, my old Android 5 device didn't support it. When trying to grant permission the Files application would launch, but there's no select button or anything that would allow access to be granted to TEdit. Because of this people would not be able to browse and save files on those devices that do not support granting permissions to specific directories.

My options here were to leave the minimum SDK level and get inundated with upset people with devices that didn't support the new framework, re-write a bunch of code so that TEdit could work the old way on an older device or just raise the minimum SDK level and let older devices continue to use TEdit version 2.3.0.

I chose the latter because no improvements had been made other than supporting the new storage framework, older devices would have seen no change so there wasn't any reason for those devices to upgrade. Depending on how far off the next version of TEdit is there's a good chance I'll decide to add the additional code to support older devices again.

The TEdit listing on Google Play has both the 2.4.3 apk and the 2.3.0 apk. When choosing to install through Google Play Google will automatically install version 2.3.0 if the device is running a version of Android older than 9.

By the by, I'm actually not sure at what point all Android devices started supporting this storage access framework. 9 seemed like a safe guess.

I hope this answers your question.

P.S. Technically version 2.4.0 introduces some animation when switching directories in the browser, but this was added in response to the additional load times the new storage framework instills. Exactly why it's so much slower I could't say, but it is so I added transition animations to help reduce the impact the additional load times had on the user experience.

**Comment by EchedelleLR** [comment]
I am using only F-Droid as store and there that version is no longer provided.

**Comment by ATryder** [comment]
When you're viewing the TEdit listing in the F-Droid app scroll to the bottom and tap "versions" and there should be an entry for 2.3.0. You can tap the "install" button next to the 2.3.0 version.

Is there an entry for 2.3.0 under the versions menu?

**Comment by EchedelleLR** [comment]
I am telling you because there is not.

I had it "showed" in the local F-Droid app because I had it installed before but neither F-Droid repositories nor F-Droid website have available that version.

F-Droid always work in that way.

I can check to see if I am lucky to find it in the Archive repository but that will add a lot of extra load of outdated apps in every F-Droid update of the dB which is already a heavy process.

**Comment by ATryder** [comment]
Hmm, maybe I'll add a TEdit Legacy as a seperate app to F-Droid. Although in my experience it takes a good six months or so before new apps are added to the repository.

The 2.3.0 version is available on my website as a direct download, https://www.inventati.org/1337gallery/apps/tedit/tedit.html so you can get it there. That's a version that was built by myself with my own signing key.

If you'd rather not install that version then, for now, I suppose your other option is to clone the TEdit v2.3.0 tag in this repository and build it yourself. It doesn't require any external libraries outside of the standard ones required by Android Studio.

**Comment by ATryder** [comment]
I added support back in for Android versions older than 9 and newer than 4 as of commit 2ee43e4d008d0a9d192b0b05a9287dce20efd251. TEdit version 2.4.4 should hit F-Droid within a week or two.

**Comment by EchedelleLR** [comment]
I confirm it works perfectly in Android 7.1.2.
