### ISSUE TITLE
Recover my temporary file

### ISSUE THREAD

**Issue by Vincent-Millane** [ATryder/TEdit#16]
Hello,

I was writing a long document when my Tedit page (installed from F-Droid) went to the right while I was typing.

Does the software use temporary files to run?

If so, where can I find them in Android 10 to find my work?
Thank you in advance for your assistance.

**Comment by ATryder** [comment]
TEdit stores unsaved data in an SQLite database stored in app-specific storage which is restricted by Android so that only TEdit should be able to access it. Typically I think this data is stored in the Android/data/package-name folder so, for TEdit, probably Android/data/com.atr.tedit.

TEdit clears this database when the app is closed and deletes entries when text documents are closed. If the database hasn't been cleared I'm not sure how you would go about reading it's contents.

Also, I don't recommend using the version of TEdit available on F-Droid, I stopped supporting F-Droid some time ago. The latest version of TEdit is available on my website at https://www.inventati.org/1337gallery/apps/tedit/tedit.html where you can find a direct download link, with checksum, as-well as links to TEdit on Google Play and Amazon.
